### ISSUE TITLE
S3 Permissions Error when deploying the template

### ISSUE THREAD

**Issue by msharma24** [aws-ia/cfn-ps-cisco-ise-on-aws#7]
When I attempt to deploy the CFN template from the deployment guide - I get an S3 Access error - it appears the `ISEStack` Template has permission issues.

URL https://aws-ia.github.io/cfn-ps-cisco-ise-on-aws/

Template S3 URL with permissions error https://aws-ia-us-east-1.s3.us-east-1.amazonaws.com/cfn-ps-cisco-ise-on-aws/templates/quickstart-cisco-ise-on-aws-workload.template.yaml

**Step to reproduce the issue**

1. Browse URL https://aws-ia.github.io/cfn-ps-cisco-ise-on-aws/
2. Click on [Deploy Cisco ISE into an existing VPC](https://fwd.aws/5vBy7?). under Deployment Options
3. The Browser redirects to AWS Console Cloudformation Template Paramaters page
4. Select existing VPC 
5. Enter LB Subnet Private IP 1 and LB Subnet Private 2
6. Click Next
7 . Acknowledge IAM Check boxes
8. Click to run the cloudformation template in the cloudformation console
9. The Cloudformation Template Events shows S3 Access Error for "ISEStack"

**Comment by vsnyc** [comment]
Fixed in https://github.com/aws-ia/cfn-ps-cisco-ise-on-aws/pull/10
